package com.myapplications.mywatchlist.ui.theme

import androidx.compose.ui.graphics.Color

val md_light_primary = Color(0xFF006C4D)
val md_light_onPrimary = Color(0xFFFFFFFF)
val md_light_primaryContainer = Color(0xFF87F8C9)
val md_light_onPrimaryContainer = Color(0xFF002115)
val md_light_secondary = Color(0xFF4C6358)
val md_light_onSecondary = Color(0xFFFFFFFF)
val md_light_secondaryContainer = Color(0xFFCFE9DA)
val md_light_onSecondaryContainer = Color(0xFF092017)
val md_light_tertiary = Color(0xFF3E6374)
val md_light_onTertiary = Color(0xFFFFFFFF)
val md_light_tertiaryContainer = Color(0xFFC1E8FC)
val md_light_onTertiaryContainer = Color(0xFF001F2A)
val md_light_error = Color(0xFFBA1A1A)
val md_light_errorContainer = Color(0xFFFFDAD6)
val md_light_onError = Color(0xFFFFFFFF)
val md_light_onErrorContainer = Color(0xFF410002)
val md_light_background = Color(0xFFFBFDF9)
val md_light_onBackground = Color(0xFF191C1A)
val md_light_surface = Color(0xFFFBFDF9)
val md_light_onSurface = Color(0xFF191C1A)
val md_light_surfaceVariant = Color(0xFFDBE5DE)
val md_light_onSurfaceVariant = Color(0xFF404944)
val md_light_outline = Color(0xFF707973)
val md_light_inverseOnSurface = Color(0xFFEFF1ED)
val md_light_inverseSurface = Color(0xFF2E312F)
val md_light_inversePrimary = Color(0xFF6ADBAE)
val md_light_shadow = Color(0xFF000000)
val md_light_surfaceTint = Color(0xFF006C4D)
val md_light_outlineVariant = Color(0xFFBFC9C2)
val md_light_scrim = Color(0xFF000000)

val md_dark_primary = Color(0xFF6ADBAE)
val md_dark_onPrimary = Color(0xFF003827)
val md_dark_primaryContainer = Color(0xFF00513A)
val md_dark_onPrimaryContainer = Color(0xFF87F8C9)
val md_dark_secondary = Color(0xFFB3CCBE)
val md_dark_onSecondary = Color(0xFF1F352B)
val md_dark_secondaryContainer = Color(0xFF354B41)
val md_dark_onSecondaryContainer = Color(0xFFCFE9DA)
val md_dark_tertiary = Color(0xFFA6CCDF)
val md_dark_onTertiary = Color(0xFF083544)
val md_dark_tertiaryContainer = Color(0xFF254B5B)
val md_dark_onTertiaryContainer = Color(0xFFC1E8FC)
val md_dark_error = Color(0xFFFFB4AB)
val md_dark_errorContainer = Color(0xFF93000A)
val md_dark_onError = Color(0xFF690005)
val md_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_dark_background = Color(0xFF191C1A)
val md_dark_onBackground = Color(0xFFE1E3DF)
val md_dark_surface = Color(0xFF191C1A)
val md_dark_onSurface = Color(0xFFE1E3DF)
val md_dark_surfaceVariant = Color(0xFF404944)
val md_dark_onSurfaceVariant = Color(0xFFBFC9C2)
val md_dark_outline = Color(0xFF8A938D)
val md_dark_inverseOnSurface = Color(0xFF191C1A)
val md_dark_inverseSurface = Color(0xFFE1E3DF)
val md_dark_inversePrimary = Color(0xFF006C4D)
val md_dark_shadow = Color(0xFF000000)
val md_dark_surfaceTint = Color(0xFF6ADBAE)
val md_dark_outlineVariant = Color(0xFF404944)
val md_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF004A34)
val IMDBOrange = Color(0xFFF5C338)
val light_IMDBOrange = Color(0xFF765A00)
val light_onIMDBOrange = Color(0xFFFFFFFF)
val light_IMDBOrangeContainer = Color(0xFFFFDF96)
val light_onIMDBOrangeContainer = Color(0xFF251A00)
val dark_IMDBOrange = Color(0xFFF2C035)
val dark_onIMDBOrange = Color(0xFF3E2E00)
val dark_IMDBOrangeContainer = Color(0xFF5A4400)
val dark_onIMDBOrangeContainer = Color(0xFFFFDF96)
